name: guanasfires
description: This a project of Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_sign_in: ^4.4.4
  firebase_auth: ^0.16.0
  percent_indicator: ^2.1.3
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+1
  intl: ^0.16.1
  json_annotation: ^2.0.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  google_maps_flutter: ^0.5.11+1
  location: ^2.3.5
  flutter_polyline_points: ^0.1.0
  gradient_app_bar: ^0.1.3
  flutter_slidable: "^0.5.3"
  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - resources/Cantones.json
    - resources/Distritos.json
    - resources/Provincias.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
